### ISSUE TITLE
AWS::RDS::DBCluster AssociatedRoles translation error

### ISSUE THREAD

**Issue by evadne** [aws-cloudformation/aws-cloudformation-resource-providers-rds#373]
Given the following abridged template, given the `IsDatabaseImportExportEnabled` condition is true, the resource is created/updated with only 1 associated role for `s3Import` 

Reason Why This Is Wrong:
- The template I have created, expects the same IAM role to be added for both `s3Import` and `s3Export` features.
- The template executed via CFN without errors and there was no drift detected.
- However s3Export did not work.
- As the cluster is Amazon Aurora with PostgreSQL compatibility I have viewed documentation at https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraMySQL.Integrating.Authorizing.IAM.AddRoleToDBCluster.html.
- When I realised that the role was only added for `s3Import` feature, via checking the DB Cluster in the AWS Console, I attempted to add the same role for `s3Export` however the console rejected this and gave me an error message saying that the same role  has already been added.
- The document linked above did not mention that the same role can only be used for one feature.

Workaround:
- I have created a 2nd IAM role and associated it for the `s3Export` feature

```yaml
DatabaseCluster:
    Type: AWS::RDS::DBCluster
    DependsOn:
      - DatabaseClusterParameterGroup
      - DatabaseInstanceParameterGroup
    Properties:
      AssociatedRoles:
        - !If
          - IsDatabaseImportExportEnabled
          - FeatureName: s3Import
            RoleArn: !GetAtt DatabaseImportExportRole.Arn
          - !Ref AWS::NoValue
        - !If
          - IsDatabaseImportExportEnabled
          - FeatureName: s3Export
            RoleArn: !GetAtt DatabaseImportExportRole.Arn
          - !Ref AWS::NoValue
      BackupRetentionPeriod: !Ref DatabaseBackupRetentionPeriod
      DatabaseName: postgres
      DBClusterParameterGroupName: !Ref DatabaseClusterParameterGroup
      DBSubnetGroupName: !Ref DatabaseSubnetGroup
      EnableCloudwatchLogsExports:
        - postgresql
      Engine: aurora-postgresql
      EngineVersion: '12.12'
      MasterUsername: !Sub '{{resolve:secretsmanager:${DatabaseMasterUsernameSecret}:SecretString::}}'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${DatabaseMasterPasswordSecret}:SecretString::}}'
      Port: 5432
      StorageEncrypted: true
      VpcSecurityGroupIds:
        - !Ref DatabaseSecurityGroup
```
