### ISSUE TITLE
EnableIAMDatabaseAuthentication not applying to cluster

### ISSUE THREAD

**Issue by lancechant** [aws-cloudformation/aws-cloudformation-resource-providers-rds#56]
Not sure if this is the correct place to submit this.

Trying to set `IAM DB authentication` to true on the already existing cluster via cloudFormation, but when setting `EnableIAMDatabaseAuthentication: true` in the cloudFormation seems to have no effect on this. Am I reading the documentation correct? I was looking at this page [AWS::RDS::DBCluster](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html#cfn-rds-dbcluster-enableiamdatabaseauthentication)

**Comment by bigpresh** [comment]
I've seen the same problem.

We're using CDK, and have defined the cluster like this:

```
    const cluster = new rds.DatabaseCluster(this, "Database", {
      engine,
      parameterGroup,
      instances: 1, // just a primary for now.
      instanceProps: {
        instanceType: ec2.InstanceType.of(
          // FIXME: get right instance size
          ec2.InstanceClass.R6G,
          ec2.InstanceSize.LARGE
        ),
        vpcSubnets: {
          subnetType: ec2.SubnetType.PUBLIC,
        },
        securityGroups: [sg],
        vpc,
        publiclyAccessible: true, // subject to the security group rules of course
      },
      iamAuthentication: true, // Allow IAM-based auth
    });
```

Note that we have set `iamAuthentication` to true now; the setting was not present when the cluster was initially created via CDK.  I have not (yet) tested whether deploying a new cluster with `iamAuthentication: true` set from the outset works.

Using `cdk synth`, I see that the generated CloudFormation output has `EnableIAMDatabaseAuthentication` setting enabled:

```
...
 DatabaseB269D8BB:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora-postgresql
      CopyTagsToSnapshot: true
      DBClusterParameterGroupName:
        Ref: ParameterGroup5E32DECB
      DBSubnetGroupName:
        Ref: DatabaseSubnets56F17B9A
      DeletionProtection: true
      EnableIAMDatabaseAuthentication: true
      EngineVersion: "12.6"
...
```

However, when I `cdk deploy` the stack, nothing changes - IAM auth is still disabled for the cluster.

After the deployment, looking via the AWS Console in CloudFormation -> Stacks -> OurDBStackName, I see the CloudFormation config above, with the value set to enabled - but it just is not actually enabling it on the cluster.

If I manually go and turn it on via the AWS Console, then IAM authentication works (and a subsequent `cdk deploy` does not revert it!)

So, as best as I can see, the `EnableIAMDatabaseAuthentication` setting is making it to CloudFormation, but being ignored.
