### ISSUE TITLE
Cannot invoke "java.lang.Double.doubleValue() error

### ISSUE THREAD

**Issue by ismail-pitchstone** [aws-cloudformation/aws-cloudformation-resource-providers-rds#587]
We have a cloudformation template which has been created long time ago. It is stopped working after Dec 19,2024 with the following error:

```
Resource handler returned message: "Cannot invoke "java.lang.Double.doubleValue()" 
because the return value of "software.amazon.rds.dbcluster.ServerlessV2ScalingConfiguration.getMinCapacity()" is null
(RequestToken: a498314f-9176-941c-f89b-xyz, HandlerErrorCode: InternalFailure)" 
```

We dont use db.serverless, our instance class  `DBInstanceClass db.t4g.large`

No idea why it hits getMinCapacity error. Is there any change in the RDS cloudformation provider recently?

```
 RDSCluster:
    Type: AWS::RDS::DBCluster
   ...
      ServerlessV2ScalingConfiguration:
        MinCapacity:
          Fn::If:
            - IsAuroraServerless
            - Ref: ServerlessMinCapacity
            - Ref: AWS::NoValue
        MaxCapacity:
          Fn::If:
            - IsAuroraServerless
            - Ref: ServerlessMaxCapacity
            - Ref: AWS::NoValue
            
IsAuroraServerless:
    Fn::Equals:
      - Ref: DBInstanceClass
      - db.serverless
 
DBInstanceClass:
    Description: Instance class for the database of this environment
    Type: String
    Default: db.t3.medium
    AllowedValues:
      - db.t3.medium
      - db.t3.large
      - db.t4g.large
      - db.r5.large
      - db.r5.xlarge
      - db.r5.2xlarge
      - db.r6g.large
      - db.r6g.xlarge
      - db.r6g.2xlarge
      - db.r7g.large
      - db.r7g.xlarge
      - db.r7g.2xlarge
      - db.serverless
     

```
